trigger:
  batch: true
  branches:
    include: [ 'master' ]

pool: Default

workspace:
  clean: outputs

steps:
  - task: ArchiveFiles@2
    displayName: 'Zip app source files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/app_sources.zip'
     
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifacts: App sources'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/app_sources.zip'
      artifact: app_sources
      
  - task: Npm@1
    displayName: 'npm install'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      customCommand: 'run build'

  - task: ArchiveFiles@2
    displayName: 'Zip tests files'
    inputs:
      rootFolderOrFile: cypress
      archiveFile: '$(Build.ArtifactStagingDirectory)/cypress.zip'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifacts: Cypress tests'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/cypress.zip'
      artifact: cypress

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifacts: package.json'
    inputs:
      targetPath: package.json
      artifact: 'package_json'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: App'
    inputs:
      PathtoPublish: dist
      ArtifactName: app
